from IPython import get_ipython

# note: this is still teh good one

@fq
_ip = get_ipython()
# Dude dont forget this one!
_ip.true_color = True

# Note: This is the not messed up one
# In [3]: _ip.style.style_rules
# Out[3]:
_ip.style.style_rules = [
    ("pygments.text.whitespace", "#bbbbbb"),
    ("pygments.comment", "italic #408080"),
    ("pygments.comment.preproc", "noitalic #BC7A00"),
    ("pygments.keyword", "bold #008000"),
    ("pygments.keyword.pseudo", "nobold"),
    ("pygments.keyword.type", "nobold #B00040"),
    ("pygments.operator", "#666666"),
    ("pygments.operator.word", "bold #AA22FF"),
    ("pygments.name.builtin", "#008000"),
    ("pygments.name.function", "#0000FF"),
    ("pygments.name.class", "bold #0000FF"),
    ("pygments.name.namespace", "bold #0000FF"),
    ("pygments.name.exception", "bold #D2413A"),
    ("pygments.name.variable", "#19177C"),
    ("pygments.name.constant", "#880000"),
    ("pygments.name.label", "#A0A000"),
    ("pygments.name.entity", "bold #999999"),
    ("pygments.name.attribute", "#7D9029"),
    ("pygments.name.tag", "bold #008000"),
    ("pygments.name.decorator", "#AA22FF"),
    ("pygments.literal.string", "#BA2121"),
    ("pygments.literal.string.doc", "italic"),
    ("pygments.literal.string.interpol", "bold #BB6688"),
    ("pygments.literal.string.escape", "bold #BB6622"),
    ("pygments.literal.string.regex", "#BB6688"),
    ("pygments.literal.string.symbol", "#19177C"),
    ("pygments.literal.string.other", "#008000"),
    ("pygments.literal.number", "#666666"),
    ("pygments.generic.heading", "bold #000080"),
    ("pygments.generic.subheading", "bold #800080"),
    ("pygments.generic.deleted", "#A00000"),
    ("pygments.generic.inserted", "#00A000"),
    ("pygments.generic.error", "#FF0000"),
    ("pygments.generic.emph", "italic"),
    ("pygments.generic.strong", "bold"),
    ("pygments.generic.prompt", "bold #000080"),
    ("pygments.generic.output", "#888"),
    ("pygments.generic.traceback", "#04D"),
    ("pygments.error", "border:#FF0000"),
    ("pygments", ""),
    ("pygments.text", ""),
    ("pygments.escape", ""),
    ("pygments.other", ""),
    ("pygments.keyword.constant", ""),
    ("pygments.keyword.declaration", ""),
    ("pygments.keyword.namespace", ""),
    ("pygments.keyword.reserved", ""),
    ("pygments.name", ""),
    ("pygments.name.builtin.pseudo", ""),
    ("pygments.name.function.magic", ""),
    ("pygments.name.property", ""),
    ("pygments.name.other", ""),
    ("pygments.name.variable.class", ""),
    ("pygments.name.variable.global", ""),
    ("pygments.name.variable.instance", ""),
    ("pygments.name.variable.magic", ""),
    ("pygments.literal", ""),
    ("pygments.literal.date", ""),
    ("pygments.literal.string.affix", ""),
    ("pygments.literal.string.backtick", ""),
    ("pygments.literal.string.char", ""),
    ("pygments.literal.string.delimiter", ""),
    ("pygments.literal.string.double", ""),
    ("pygments.literal.string.heredoc", ""),
    ("pygments.literal.string.single", ""),
    ("pygments.literal.number.bin", ""),
    ("pygments.literal.number.float", ""),
    ("pygments.literal.number.hex", ""),
    ("pygments.literal.number.integer", ""),
    ("pygments.literal.number.integer.long", ""),
    ("pygments.literal.number.oct", ""),
    ("pygments.punctuation", ""),
    ("pygments.comment.hashbang", ""),
    ("pygments.comment.multiline", ""),
    ("pygments.comment.preprocfile", ""),
    ("pygments.comment.single", ""),
    ("pygments.comment.special", ""),
    ("pygments.generic", ""),
    ("pygments.literal.number", "#007700"),
    ("pygments.operator", "noinherit"),
    ("pygments.literal.string", "#BB6622"),
    ("pygments.name.function", "#2080D0"),
    ("pygments.name.class", "bold #2080D0"),
    ("pygments.name.namespace", "bold #2080D0"),
    ("pygments.prompt", "#009900"),
    ("pygments.promptnum", "#ansibrightgreen bold"),
    ("pygments.outprompt", "#990000"),
    ("pygments.outpromptnum", "#ansibrightred bold"),
]

# _ip.pt_app.app.style.style_rules = None
# _ip.pt_app.app.style.style_rules = [
#     ("pygments.comment", "#928374"),
#     ("pygments.comment.hashbang", "#928374"),
#     ("pygments.comment.multiline", "#fabd2f italic"),
#     ("pygments.comment.single", "#928374 italic"),
#     ("pygments.escape", "#665c54"),
#     ("pygments.error", "#fb4934 bold"),
#     ("pygments.generic", "#ebdbb2"),
#     ("pygments.generic.deleted", "#f9f5d7"),
#     ("pygments.generic.emph", "underline #83a598"),
#     ("pygments.generic.heading", "#b8bb26 bold"),
#     ("pygments.generic.inserted", "#f9f5d7"),
#     ("pygments.generic.output", "#d5c4a1"),
#     ("pygments.generic.prompt", "#83a598"),
#     ("pygments.generic.strong", "#ebdbb2 bold"),
#     ("pygments.generic.subheading", "#b8bb26 bold"),
#     ("pygments.keyword", "#fe8019"),
#     ("pygments.keyword.constant", "#fe8019"),
#     ("pygments.keyword.declaration", "#fe8019"),
#     ("pygments.keyword.pseudo", "#d3869b"),
#     ("pygments.keyword.type", "#fabd2f"),
#     ("pygments.name", "#ebdbb2"),
#     ("pygments.name.attribute", "#b8bb26"),
#     ("pygments.name.builtin", "#fabd2f"),
#     ("pygments.name.class", "#d65d0e"),
#     ("pygments.name.constant", "#d3869b"),
#     ("pygments.name.decorator", "#fabd2f"),
#     ("pygments.name.entity", "#fabd2f"),
#     ("pygments.name.exception", "bold #fb4934"),
#     ("pygments.name.function", "noinherit #fabd2f"),
#     ("pygments.name.function.magic", "noinherit #8ec07c"),
#     ("pygments.name.label", "#fb4934"),
#     ("pygments.name.namespace", "#83a598"),
#     ("pygments.name.property", "#8ec07c"),
#     ("pygments.name.tag", "#fb4934"),
#     ("pygments.name.variable", "#ebdbb2"),
#     ("pygments.name.variable.class", "noinherit #83a598"),
#     ("pygments.name.variable.global", "noinherit #83a598"),
#     ("pygments.name.variable.instance", "noinherit #83a598"),
#     ("pygments.name.variable.magic", "noinherit #83a598"),
#     ("pygments.literal", "#fe8019"),
#     ("pygments.literal.date", "#b8bb26"),
#     ("pygments.literal.string", "#b8bb26"),
#     ("pygments.literal.string.backtick", "#a89984"),
#     ("pygments.literal.string.char", "#ebdbb2"),
#     ("pygments.literal.string.doc", "#928374"),
#     ("pygments.literal.string.interpol", "#b8bb26"),
#     ("pygments.literal.string.regex", "#fabd2f"),
#     ("pygments.literal.string.symbol", "#83a598"),
#     ("pygments.literal.number", "#fe8019"),
#     ("pygments.punctuation", "#ebdbb2"),
#     ("pygments.operator", "#8ec07c"),
#     ("pygments.text", "#ebdbb2"),
#     ("pygments.text.whitespace", ""),
#     ("pygments.prompt", "#b8bb26"),
#     ("pygments.promptnum", "bold #b8bb26"),
#     ("pygments.outprompt", "#b8bb26"),
#     ("pygments.outpromptnum", "#b8bb26"),
#     ("pygments", ""),
#     ("pygments.other", ""),
#     ("pygments.keyword.namespace", ""),
#     ("pygments.keyword.reserved", ""),
#     ("pygments.name.builtin.pseudo", ""),
#     ("pygments.name.other", ""),
#     ("pygments.literal.string.affix", ""),
#     ("pygments.literal.string.delimiter", ""),
#     ("pygments.literal.string.double", ""),
#     ("pygments.literal.string.escape", ""),
#     ("pygments.literal.string.heredoc", ""),
#     ("pygments.literal.string.other", ""),
#     ("pygments.literal.string.single", ""),
#     ("pygments.literal.number.bin", ""),
#     ("pygments.literal.number.float", ""),
#     ("pygments.literal.number.hex", ""),
#     ("pygments.literal.number.integer", ""),
#     ("pygments.literal.number.integer.long", ""),
#     ("pygments.literal.number.oct", ""),
#     ("pygments.operator.word", ""),
#     ("pygments.comment.preproc", ""),
#     ("pygments.comment.preprocfile", ""),
#     ("pygments.comment.special", ""),
#     ("pygments.generic.error", ""),
#     ("pygments.generic.traceback", ""),
#     ("pygments.prompt", "#009900"),
#     ("pygments.promptnum", "#ansibrightgreen bold"),
#     ("pygments.outprompt", "#990000"),
#     ("pygments.outpromptnum", "#ansibrightred bold"),
# ]

# _ip.pt_app.style.style_rules = None
# _ip.pt_app.style.style_rules = [
#     # In [33]: _ip.pt_app.style.style_rules
#     # Out[33]:
#     ("pygments.comment", "#928374"),
#     ("pygments.comment.hashbang", "#928374"),
#     ("pygments.comment.multiline", "#fabd2f italic"),
#     ("pygments.comment.single", "#928374 italic"),
#     ("pygments.escape", "#665c54"),
#     ("pygments.error", "#fb4934 bold"),
#     ("pygments.generic", "#ebdbb2"),
#     ("pygments.generic.deleted", "#f9f5d7"),
#     ("pygments.generic.emph", "underline #83a598"),
#     ("pygments.generic.heading", "#b8bb26 bold"),
#     ("pygments.generic.inserted", "#f9f5d7"),
#     ("pygments.generic.output", "#d5c4a1"),
#     ("pygments.generic.prompt", "#83a598"),
#     ("pygments.generic.strong", "#ebdbb2 bold"),
#     ("pygments.generic.subheading", "#b8bb26 bold"),
#     ("pygments.keyword", "#fe8019"),
#     ("pygments.keyword.constant", "#fe8019"),
#     ("pygments.keyword.declaration", "#fe8019"),
#     ("pygments.keyword.pseudo", "#d3869b"),
#     ("pygments.keyword.type", "#fabd2f"),
#     ("pygments.name", "#ebdbb2"),
#     ("pygments.name.attribute", "#b8bb26"),
#     ("pygments.name.builtin", "#fabd2f"),
#     ("pygments.name.class", "#d65d0e"),
#     ("pygments.name.constant", "#d3869b"),
#     ("pygments.name.decorator", "#fabd2f"),
#     ("pygments.name.entity", "#fabd2f"),
#     ("pygments.name.exception", "bold #fb4934"),
#     ("pygments.name.function", "noinherit #fabd2f"),
#     ("pygments.name.function.magic", "noinherit #8ec07c"),
#     ("pygments.name.label", "#fb4934"),
#     ("pygments.name.namespace", "#83a598"),
#     ("pygments.name.property", "#8ec07c"),
#     ("pygments.name.tag", "#fb4934"),
#     ("pygments.name.variable", "#ebdbb2"),
#     ("pygments.name.variable.class", "noinherit #83a598"),
#     ("pygments.name.variable.global", "noinherit #83a598"),
#     ("pygments.name.variable.instance", "noinherit #83a598"),
#     ("pygments.name.variable.magic", "noinherit #83a598"),
#     ("pygments.literal", "#fe8019"),
#     ("pygments.literal.date", "#b8bb26"),
#     ("pygments.literal.string", "#b8bb26"),
#     ("pygments.literal.string.backtick", "#a89984"),
#     ("pygments.literal.string.char", "#ebdbb2"),
#     ("pygments.literal.string.doc", "#928374"),
#     ("pygments.literal.string.interpol", "#b8bb26"),
#     ("pygments.literal.string.regex", "#fabd2f"),
#     ("pygments.literal.string.symbol", "#83a598"),
#     ("pygments.literal.number", "#fe8019"),
#     ("pygments.punctuation", "#ebdbb2"),
#     ("pygments.operator", "#8ec07c"),
#     ("pygments.text", "#ebdbb2"),
#     ("pygments.text.whitespace", ""),
#     ("pygments.prompt", "#b8bb26"),
#     ("pygments.promptnum", "bold #b8bb26"),
#     ("pygments.outprompt", "#b8bb26"),
#     ("pygments.outpromptnum", "#b8bb26"),
#     ("pygments", ""),
#     ("pygments.other", ""),
#     ("pygments.keyword.namespace", ""),
#     ("pygments.keyword.reserved", ""),
#     ("pygments.name.builtin.pseudo", ""),
#     ("pygments.name.other", ""),
#     ("pygments.literal.string.affix", ""),
#     ("pygments.literal.string.delimiter", ""),
#     ("pygments.literal.string.double", ""),
#     ("pygments.literal.string.escape", ""),
#     ("pygments.literal.string.heredoc", ""),
#     ("pygments.literal.string.other", ""),
#     ("pygments.literal.string.single", ""),
#     ("pygments.literal.number.bin", ""),
#     ("pygments.literal.number.float", ""),
#     ("pygments.literal.number.hex", ""),
#     ("pygments.literal.number.integer", ""),
#     ("pygments.literal.number.integer.long", ""),
#     ("pygments.literal.number.oct", ""),
#     ("pygments.operator.word", ""),
#     ("pygments.comment.preproc", ""),
#     ("pygments.comment.preprocfile", ""),
#     ("pygments.comment.special", ""),
#     ("pygments.generic.error", ""),
#     ("pygments.generic.traceback", ""),
#     ("pygments.prompt", "#009900"),
#     ("pygments.promptnum", "#ansibrightgreen bold"),
#     ("pygments.outprompt", "#990000"),
#     ("pygments.outpromptnum", "#ansibrightred bold"),
# ]

# _ip = get_ipython()

_ip.style.style_rules = [
    # In [7]: _ip.style
    # Out[7]: <prompt_toolkit.styles.base.DynamicStyle at 0x7f24015acb80>
    # In [8]: _ip.style.style_rules
    # Out[8]:
    ("pygments.text", "#fbf1c7"),
    ("pygments.text.whitespace", ""),
    ("pygments.error", "#fb4934"),
    ("pygments.other", ""),
    ("pygments.comment", "#ebdbb2"),
    ("pygments.comment.multiline", ""),
    ("pygments.comment.preproc", ""),
    ("pygments.comment.single", ""),
    ("pygments.comment.special", ""),
    ("pygments.keyword", "#fb4934"),
    ("pygments.keyword.constant", ""),
    ("pygments.keyword.declaration", ""),
    ("pygments.keyword.namespace", "#83a598"),
    ("pygments.keyword.pseudo", ""),
    ("pygments.keyword.reserved", ""),
    ("pygments.keyword.type", "#fabd2f"),
    ("pygments.operator", "#83a598"),
    ("pygments.operator.word", ""),
    ("pygments.punctuation", "#fbf1c7"),
    ("pygments.name", "#fbf1c7"),
    ("pygments.name.attribute", "#458588"),
    ("pygments.name.builtin", ""),
    ("pygments.name.builtin.pseudo", ""),
    ("pygments.name.class", "#fb4934"),
    ("pygments.name.constant", "#fb4934"),
    ("pygments.name.decorator", "#98971a"),
    ("pygments.name.entity", ""),
    ("pygments.name.exception", "#fb4934"),
    ("pygments.name.function", "#458588"),
    ("pygments.name.property", ""),
    ("pygments.name.label", ""),
    ("pygments.name.namespace", "#fabd2f"),
    ("pygments.name.other", "#458588"),
    ("pygments.name.tag", "#83a598"),
    ("pygments.name.variable", "#fb4934"),
    ("pygments.name.variable.class", ""),
    ("pygments.name.variable.global", ""),
    ("pygments.name.variable.instance", ""),
    ("pygments.literal.number", "#fe8019"),
    ("pygments.literal.number.float", ""),
    ("pygments.literal.number.hex", ""),
    ("pygments.literal.number.integer", ""),
    ("pygments.literal.number.integer.long", ""),
    ("pygments.literal.number.oct", ""),
    ("pygments.literal", "#fe8019"),
    ("pygments.literal.date", "#98971a"),
    ("pygments.literal.string", "#98971a"),
    ("pygments.literal.string.backtick", ""),
    ("pygments.literal.string.char", "#fbf1c7"),
    ("pygments.literal.string.doc", "#ebdbb2"),
    ("pygments.literal.string.double", ""),
    ("pygments.literal.string.escape", "#fe8019"),
    ("pygments.literal.string.heredoc", ""),
    ("pygments.literal.string.interpol", "#fe8019"),
    ("pygments.generic.heading", "bold #fbf1c7"),
    ("pygments.generic.inserted", "#98971a"),
    ("pygments.generic.output", ""),
    ("pygments.generic.prompt", "bold #ebdbb2"),
    ("pygments.generic.strong", "bold"),
    ("pygments.generic.subheading", "bold #83a598"),
    ("pygments.generic.traceback", "#fb4934"),
]
